### ISSUE TITLE
Understanding Check Questions

### ISSUE THREAD

**Issue by jzureich** [Nmoleo64/MeliorationWeb#16] opened 2018-07-18 16:09 UTC

**Comment by jzureich** [comment] 2018-07-18 16:16
[UnderstandingChecks_1.1.docx](https://github.com/Nmoleo64/MeliorationWeb/files/2206524/UnderstandingChecks_1.1.docx)

**Comment by jzureich** [comment] 2018-07-18 16:18
Nicholas, I think we should change the instructions text and the understanding check questions text as our last step, because I will keep rereading them and (potentially) making small changes.

**Comment by Nmoleo64** [comment] 2018-07-18 17:51
That sounds good - Vic said he will go over the instructions very carefully before we deploy.

**Comment by Nmoleo64** [comment] 2018-07-18 17:52
Closing this issue as it is a duplicate of #9

**Closed by Nmoleo64** 2018-07-18 17:52 UTC
Labels: Duplicate, Feature
